services:
  api:
    image: cosmtrek/air:v1.64.5
    container_name: api
    volumes:
      - .:/mnt
    ports:
      - ${API_PORT:-8080}:8080
    working_dir: /mnt
    entrypoint: ["air"]
    depends_on:
      seed:
        restart: true
        condition: service_completed_successfully

include:
  - "./example/${BACKEND:-duckdb}/docker-compose.yaml"
