name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1


  validate-api:
    name: Validate STAC API
    runs-on: ubuntu-latest

    strategy:
      matrix:
        backend: ["duckdb", "pgstac"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.10.4"
      - name: Set up Python
        run: uv python install
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run server
        uses: JarvusInnovations/background-action@v1
        env:
          BACKEND: ${{ matrix.backend }}
        with:
          run: docker compose -f ./docker/docker-compose.yaml up
          wait-on: |
            http-get://localhost:8080/
          tail: true # true = stderr,stdout
          log-output-resume: stderr
          log-output-if: true
          wait-for: 2m
      - name: Run stac-api-validator
        timeout-minutes: 5
        run: |
          uv run stac-api-validator \
            --root-url http://localhost:8080 \
            --conformance core --conformance collections \
            --collection naip
